### ISSUE TITLE
The new trim materials are incompatible with every modded armor trim

### ISSUE THREAD

**Issue by santastolle** [LeoMinecraftModding/Eternal-Starlight#11]
If you use the new armor trim materials together with any modded armor trim (More Armor Trims, Frostiful etc.) the armor turns purple. This isn't that big of a deal unless you use Mob Armor Trims, which I unfortunately do.

![2024-09-16_00 57 05](https://github.com/user-attachments/assets/f5029f54-c0ce-413d-b2da-d2f505ac624d)
![2024-09-16_00 57 58](https://github.com/user-attachments/assets/6df97982-1806-449e-8064-4230f5b0267a)

MC v1.21
ES v0.1.13

**Comment by LeoLezury** [comment]
Now all modded trim patterns or materials are automatically compatible, will be fixed in 0.1.14
<img width="1280" alt="trim_fix_1" src="https://github.com/user-attachments/assets/9016dac0-c9e2-4084-83a7-e8e659d37334">
<img width="1280" alt="trim_fix" src="https://github.com/user-attachments/assets/90113d3f-d428-412f-9a6d-e532f7927f6b">
