### ISSUE TITLE
Overworld structures in Eternal Dimension (Neoforge 1.21.1)

### ISSUE THREAD

**Issue by ElTryken** [LeoMinecraftModding/Eternal-Starlight#24]
Hello, I just installed the mod to explore and it's great. Unfortunately I found that overworld structures are generated in this dimension (Iron's Spells 'n Spellbooks, Dungeons Arise for example) so I wanted to inform you. Greetings

![image](https://github.com/user-attachments/assets/a563c790-0b8b-4e92-ae4b-e13b1aca2a0a)

![image](https://github.com/user-attachments/assets/0bc6d4af-f747-4b3e-88fa-047e2736f474)

**Comment by YocyCraft** [comment]
Maybe it's caused by data-driven structure generation.

For example, in file `data/irons_spellbooks/tags/worldgen/biome/has_structure/evoker_fort`:
```
{
  "replace": false,
  "_comment": " This biome tag can specify the biome directly. Or specify another biome tag by starting with # ",
  "values": [
    "#minecraft:is_hill",
    "#minecraft:is_forest",
    "#c:is_desert",
    "#c:is_plains",
    "minecraft:windswept_savanna",
    "minecraft:savanna",
    "minecraft:savanna_plateau"
  ]
}
```
To solve this issue on eternal starlight side, we need to remove all `#c:is_{some_type}` tags for eternal starlight biomes. However these tags are not only used for determining structure generation, but also for some other game mechanics.

**Comment by uhloin** [comment]
See also:
https://github.com/iron431/irons-spells-n-spellbooks/issues/654

**Comment by LeoLezury** [comment]
Will fix soon, I'll just delete those c tags
