### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Pooyoung** [LeoMinecraftModding/Eternal-Starlight#6]
Whenever we tried to load chunks in Eternal Starlight, it started with slow loading chunks (even though we have a 10gb of ram) then I manage to explore the 4-6k chunks away from the portal without managing the server crash, but when I reach to the point where there was a maze structure it started again, I tried it on the single player world I still got the issue instead of game crash I received low fps

**Comment by LeoLezury** [comment]
Thanks for reporting! Did the server crash or it's just lag? If the server did crash, is there a latest.log? If it's just lag could you please provider a [spark](https://modrinth.com/mod/spark) report (run /spark profiler start and wait for a few minutes before running /spark profiler stop, and copy the spark report link, (run /sparkclient profiler start / stop and do the same thing too on clients))? Thank you very much!

**Comment by LeoLezury** [comment]
Also is there a specific mod version? (0.1.x fabric or neoforge?) Thanks alot.

**Comment by LeoLezury** [comment]
It seems hard to reproduce. I tested the mod on a server with a maximum ram "4gb" but the chunk still generates normally, same speed as the overworld, and I went to the maze structure, the fps is still around 85 fps (normally 100 on my client) (the fps reduce is caused by many block entities in the maze, but it's tolerable)

**Comment by LeoLezury** [comment]
It's probably fixed. I rewrote the noise cave generation. 0.1.9 will be out soon, thanks👍
